apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: datascience-notebook
  name: datascience-notebook
spec:
  ports:
  - port: 80
  selector:
    app: datascience-notebook
status:
  loadBalancer: {}
