apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: csm-nosqlclient
  name: csm-nosqlclient
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: csm-nosqlclient
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: csm-mongodb
  name: csm-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: csm-mongodb
status:
  loadBalancer: {}