apiVersion: v1
kind: Service
metadata:
  name: csm-nosqlclient
spec:
  type: NodePort
  selector:
    app: csm-nosqlclient
  ports:
  - name: http-nginx
    nodePort: 32012
    port: 8080
    targetPort: 80
  - name: http
    nodePort: 32011
    port: 80
    protocol: TCP
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 labels:
   name: csm-mongodb
 name: csm-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: csm-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csm-nosqlclient
spec:
  selector:
    matchLabels:
      app: csm-nosqlclient
  template:
    metadata:
      labels:
        app: csm-nosqlclient
    spec:
      volumes:
      - name: nginx-configmap
        configMap:
          name: nginx-configmap
      - name: shared-data
        hostPath:
          path: /home/rafael/CBMMG/Projects/mongo/backup
          type: Directory
      containers:
      - image: mongoclient/mongoclient:latest
        name: nosqlclient
        volumeMounts:
        - name: shared-data
          mountPath: /data/backup
        env:
        # - name: MONGOCLIENT_AUTH
        #   value: "true"
        # - name: MONGOCLIENT_USERNAME
        #   value: "rootcd"
        # - name: MONGOCLIENT_PASSWORD
        #   value: "exampledd"
        - name: MONGO_URL
          value: "mongodb://csm-mongodb.dev.svc.cluster.local:27017/meteor"
        ports:
        - containerPort: 3000
      - image: nginx:latest
        name: nginx
        volumeMounts:
        - name: nginx-configmap
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: nginx-configmap
          mountPath: /etc/nginx/.htaccess
          subPath: .htaccess
          readOnly: true
        - name: shared-data
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csm-mongodb
spec:
  selector:
    matchLabels:
      app: csm-mongodb
  template:
    metadata:
      labels:
        app: csm-mongodb
    spec:
      volumes:
      - name: data
        hostPath:
          path: /home/rafael/CBMMG/Projects/mongo/data
          type: Directory
      containers:
      - image: mongo:latest
        name: mongodb
        volumeMounts:
        - name: data
          mountPath: /data/db
        # env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   value: "rootcd"
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   value: "exampledd"
        ports:
        - containerPort: 27017
